version: '3.3'

services:
  rabbitmq:
    build:
      context: rabbitmq/
    container_name: rabbitmq
    user: root
    environment:
      - VIRTUAL_HOST=rabbitmq.hmapl2160.pge.ce.gov.br
      - VIRTUAL_PORT=15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
      - '25676:25676'

  reverse-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

volumes:
  rabbitmq-data: